export const notiflixSettings = {
  width: '445px',
  position: 'center-bottom',
  distance: '100px',
  opacity: 1,
  borderRadius: '0',
  rtl: false,
  timeout: 3500,
  messageMaxLength: 110,
  backOverlay: false,
  backOverlayColor: 'rgba(0,0,0,0.5)',
  plainText: true,
  showOnlyTheLastOne: true,
  clickToClose: false,
  pauseOnHover: true,

  ID: 'NotiflixNotify',
  className: 'notiflix-notify',
  zindex: 4001,
  fontFamily: 'Quicksand',
  fontSize: '28px',
  cssAnimation: true,
  cssAnimationDuration: 400,
  cssAnimationStyle: 'fade',
  closeButton: false,
  useIcon: true,
  useFontAwesome: false,
  fontAwesomeIconStyle: 'basic',
  fontAwesomeIconSize: '28px',

  info: {
    background: '#2d3047',
    textColor: '#fffd82',
    childClassName: 'notiflix-notify-info',
    notiflixIconColor: '#e53a35',
    fontAwesomeClassName: 'fas fa-info-circle',
    fontAwesomeIconColor: 'rgba(38,192,211,0.2)',
    backOverlayColor: 'rgba(38,192,211,0.2)',
  },
};
